### ISSUE TITLE
Stack traces are too long - limit to 10

### ISSUE THREAD

**Issue by CoCraig** [ringcentral/bugsnag-notification-app#3]
The stack traces are too long and should be limited to 10 lines. Stack traces can be extra long and fill the entire screen.  The number of lines should be limited to 10.  If there is more than 10, add ellipses(three little dots like ...) to the end of the stack trace.  See other BugSnag integration for example.
<img width="510" alt="old bugnag" src="https://user-images.githubusercontent.com/64171562/110136035-0f40eb80-7d84-11eb-8050-1ec37fd92d8b.png">

**Comment by jarthod** [comment]
Here is an example :)
![image](https://user-images.githubusercontent.com/201687/110300118-ce044200-7ff6-11eb-87d7-5fd540751bc8.png)

**Comment by embbnux** [comment]
fixed now
