### ISSUE TITLE
Suggestion for more compact design

### ISSUE THREAD

**Issue by jarthod** [ringcentral/bugsnag-notification-app#4]
The Glip layout has quite some spacing when displaying this kind of cards:
![image](https://user-images.githubusercontent.com/201687/110300318-06a41b80-7ff7-11eb-94ab-95c142c3fbf9.png)

Here is a small suggestion to reduce the space list here: IMO we don't really need the "Error" and "Backtrace" titles as they are kind of obvious and redundant (it's always the same). I suggest to display the exception itself as the "title" for the Backtrace, so something like:

### Realtime::MobileMessaging - No source found for app "ooredooqa_58514b"
- app/realtime/mobile_messaging.rb:43 - perform
- app/workers/realtime_worker.rb:30 - block in perform
- app/workers/realtime_worker.rb:56 - block in with_peastash
- gems/peastash-0.2.6/lib/peastash.rb:83 - log

What do you think?

It would probably be nice to save some space near the end too:
![image](https://user-images.githubusercontent.com/201687/110300745-8a5e0800-7ff7-11eb-973e-894b7203acae.png)
As the "Severity" and "Status" is also taking quite some space, but I don't have any good suggestion for the moment, I guess this part will change with #1 so maybe it should wait.

**Comment by CoCraig** [comment]
I agree with the removal of "Error" and bolding the error message. However there may still be issues with how we present the stack trace so I think the stack trace should remain for now. In the future with adaptive cards, we may be able to remove the white space.

**Comment by jarthod** [comment]
Sure, no problem ;)

**Comment by embbnux** [comment]
Supported
